spring:
  application:
    name: donations
  datasource:
    url: jdbc:postgresql://localhost:5432/donations
    driver-class-name: org.postgresql.Driver
    username: donations
    password: donations
  flyway:
    enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  devtools:
    add-properties: false
  jackson:
    default-property-inclusion: non_null
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: prod
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
