CREATE TABLE donors (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name   VARCHAR(255) NOT NULL,
    dni_nie     VARCHAR(20)  NOT NULL UNIQUE,
    email       VARCHAR(255),
    phone       VARCHAR(50),
    address     TEXT,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_by  VARCHAR(100),
    created_at  TIMESTAMPTZ,
    updated_by  VARCHAR(100),
    updated_at  TIMESTAMPTZ
);
