CREATE TABLE donations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount          DECIMAL(10,2)  NOT NULL,
    donation_date   DATE           NOT NULL,
    donation_type   VARCHAR(50)    NOT NULL,
    payment_method  VARCHAR(50)    NOT NULL,
    donor_id        BIGINT         REFERENCES donors(id),
    notes           TEXT,
    created_by      VARCHAR(100),
    created_at      TIMESTAMPTZ,
    updated_by      VARCHAR(100),
    updated_at      TIMESTAMPTZ
);

CREATE INDEX idx_donations_donation_date ON donations(donation_date);
CREATE INDEX idx_donations_donor_id ON donations(donor_id);
