CREATE TABLE expenses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount          DECIMAL(10,2)  NOT NULL,
    expense_date    DATE           NOT NULL,
    category        VARCHAR(50)    NOT NULL,
    description     TEXT           NOT NULL,
    vendor          VARCHAR(255),
    payment_method  VARCHAR(50)    NOT NULL,
    created_by      VARCHAR(100),
    created_at      TIMESTAMPTZ,
    updated_by      VARCHAR(100),
    updated_at      TIMESTAMPTZ
);

CREATE INDEX idx_expenses_expense_date ON expenses(expense_date);
